name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  ENV: test
jobs:
  - job: "Compile"
    steps:
      - task: Maven@3
        displayName: Compiling Image
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          goals: 'compile'
      - task: Maven@3
        displayName: Testing Image
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          codeCoverageToolOption: JaCoCo
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'test'
      - task: Docker@2
        displayName: Building Docker Image
        inputs:
          command: buildAndPush
          Dockerfile: Dockerfile
          tags: |
            $(Build.BuildId)
            latest

