name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  ENV: test
jobs:
  - job: "Compile"
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: SonarCloudPrepare@1
      displayName: 
      inputs:
        SonarCloud: 'https://sonarcloud.io/organizations/semester3/projects'
        organization: 'semester3'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectKey=S3-Individual_GamingLads
          sonar.projectName=GamingLads
    - task: Maven@3
      displayName: Compiling Image
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'compile'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
    - task: SonarCloudPublish@1
      displayName: Publish SonarCloud
      inputs:
        pollingTimeoutSec: '300'
    - task: Docker@2
      displayName: Building Docker Image
      inputs:
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: |
          $(Build.BuildId)
          latest
    - task: PushToHeroku@0
      inputs:
        ApiKey: 'd0e26bf9-46d6-49bb-a3a0-aaab5063d904'
        AppName: 'gaminglads-userservice'
        PushRoot: ''


